name: flutter-ros test

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-base

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup ROS
        run: bash -c "source /opt/ros/noetic/setup.bash"
        # used bash because gitHub actions by default runs commands in sh, which does not support source

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: install flutter dependencies
        run: flutter pub get

      - name: run flutter tests
        run: flutter test

