name: flutter-ros test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: checkout repository
          uses: actions/checkout@v4

        - name: setup ros
          run: |

            sudo apt update
            sudo apt install -y curl
            sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
            curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
            sudo apt update
            sudo apt install -y ros-noetic-ros-base
            echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
            source ~/.bashrc

        - name: setting up flutter
          uses: subosito/flutter-action@v2v2
          with: 
              flutter-version: '3.19.0'

        - name: Install flutter deps
          run:  flutter pub get

        - name: Run flutter tests
          run:  flutter test

