name: flutter-ros-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ROS
        run: |
          sudo apt update
          sudo apt install -y curl
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo apt update
          sudo apt install -y ros-noetic-ros-base
          echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
          source ~/.bashrc
          echo "ROS installed successfully!"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.19.0'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test
