name: flutter-ros-test

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    container:
      image: osrf/ros:noetic

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install dependencies
        run: |
          apt update && apt install -y curl
          source /opt/ros/noetic/setup.bash

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

