name: flutter-ros test

on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ros:noetic-ros-base

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROS
        run: |
          echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
          source ~/.bashrc

      - name: Install Dependencies (jq & curl)
        run: apt-get update && apt-get install -y jq curl

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test
